### PR TITLE
fix type errors and compilation errors

### LINKED ISSUE #84: build broken on main
Current main's build (i.e `yarn build`) is broken by d619715db64436a558f7d450420ee88aac1a4034 because of the way the code now gets the production/playground config.

### PR DESCRIPTION
**Pull request by vu3rdd**
DEFAULT_PROD_CLIENT_CONFIG is not needed anymore as we fill in
defaultConfig from the environment variables for playground and
production.

closes #84 

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests.
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date, if impacted.

### CODE REVIEW

File: src/errors.ts [hunk 1]
```diff
@@ -33,8 +33,8 @@ export class AlertError extends Error {
 
     public matches(errorMsg: string, config: ClientConfig): boolean {
         const pattern = this.opts.pattern
-            .replace('$rendezvousURL', config.rendezvousURL)
-            .replace('$transitRelayURL', config.transitRelayURL);
+            .replace('$rendezvousURL', config.rendezvousURL!)
+            .replace('$transitRelayURL', config.transitRelayURL!);
```
Comment (vu3rdd) [inline src/errors.ts:37]: I am concerned by the need to put an exclamation mark, which means, we are pretty sure at this point in code that those two variables (`rendezvousURL` and `transitRelayURL`) are not undefined. This would not be true if we are running the application on `localhost` during development.

File: src/store/index.ts [hunk 2]
```diff
@@ -40,8 +40,8 @@ if (typeof(host) === 'undefined') {
 }
 
 const defaultConfig = {
-    rendezvousURL: process.env['STAGE_MAILBOX_URL'],
-    transitRelayURL: process.env['STAGE_RELAY_URL'],
+    rendezvousURL: process.env['STAGE_MAILBOX_URL'] || 'ws://localhost:4000/v1',
```
Comment (shareef-dweikat) [inline src/store/index.ts:43]: I see this link is used twice, so i suggest moving it to constants file if exists.

**Review by shareef-dweikat — APPROVED** [review]
